In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/student_lifestyle_100k.csv')

In [3]:
df.head()

,Student_ID,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
0,1001,22,Female,Science,3.50,7.3,3.3,3.4,114,5,False
1,1002,20,Male,Engineering,2.72,5.5,7.2,6.0,142,2,False
2,1003,20,Male,Medical,3.01,5.4,2.3,1.8,137,3,False
3,1004,21,Male,Engineering,3.63,8.1,2.0,4.6,130,3,False
4,1005,19,Male,Arts,3.14,6.8,2.6,4.3,4,6,False

In [4]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Department', 'CGPA', 'Sleep_Duration',
       'Study_Hours', 'Social_Media_Hours', 'Physical_Activity',
       'Stress_Level', 'Depression'],
      dtype='str')

In [7]:
new_cols = [col.lower() for col in df.columns]
df.columns = new_cols
df.columns

Index(['student_id', 'age', 'gender', 'department', 'cgpa', 'sleep_duration',
       'study_hours', 'social_media_hours', 'physical_activity',
       'stress_level', 'depression'],
      dtype='str')

In [10]:
# df.drop(columns=['student_id'], inplace=True)
df.head()

,age,gender,department,cgpa,sleep_duration,study_hours,social_media_hours,physical_activity,stress_level,depression
0,22,Female,Science,3.50,7.3,3.3,3.4,114,5,False
1,20,Male,Engineering,2.72,5.5,7.2,6.0,142,2,False
2,20,Male,Medical,3.01,5.4,2.3,1.8,137,3,False
3,21,Male,Engineering,3.63,8.1,2.0,4.6,130,3,False
4,19,Male,Arts,3.14,6.8,2.6,4.3,4,6,False

In [11]:
df.columns

Index(['age', 'gender', 'department', 'cgpa', 'sleep_duration', 'study_hours',
       'social_media_hours', 'physical_activity', 'stress_level',
       'depression'],
      dtype='str')

In [12]:
df.shape

(100000, 10)

In [19]:
df = pd.get_dummies(df, drop_first=False)
df.columns

Index(['age', 'cgpa', 'sleep_duration', 'study_hours', 'social_media_hours',
       'physical_activity', 'stress_level', 'depression', 'gender_Female',
       'gender_Male', 'department_Arts', 'department_Business',
       'department_Engineering', 'department_Medical', 'department_Science'],
      dtype='str')

In [20]:
#train test split
from sklearn.model_selection import train_test_split

X = df.drop(columns=['depression'])
y = df['depression']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [21]:
X_train.shape, y_train.shape

((70000, 14), (70000,))

In [23]:
# train a naive bayes classifier
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
# create dummy variables for categorical features

model.fit(X_train, y_train)

# evaluate the model
from sklearn.metrics import classification_report, confusion_matrix
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.90      1.00      0.95     26992
        True       0.00      0.00      0.00      3008

    accuracy                           0.90     30000
   macro avg       0.45      0.50      0.47     30000
weighted avg       0.81      0.90      0.85     30000

d:\Lectures\IIT\Batch4\Batch 4 Machine Learning\Machine Learning\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Lectures\IIT\Batch4\Batch 4 Machine Learning\Machine Learning\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Lectures\IIT\Batch4\Batch 4 Machine Learning\Machine Learning\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [25]:
# print confusion matrix
cm = confusion_matrix(y_test, y_pred)

tp ,fn, fp, tn = cm.ravel()

print(f'TP: {tp}, FN: {fn}, FP: {fp}, TN: {tn}')

TP: 26992, FN: 0, FP: 3008, TN: 0

In [26]:
y_test.value_counts()

depression
False    26992
True      3008
Name: count, dtype: int64

In [27]:

df["depression"].value_counts()

depression
False    89938
True     10062
Name: count, dtype: int64

In [ ]:
#down sampling
#upsampling